[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "nodejs_18"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt",
  "cd learningplatform_nowy2/backend && pip install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python manage.py migrate && cd learningplatform_nowy2/backend && gunicorn learning_platform.wsgi:application --bind 0.0.0.0:$PORT"