[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python manage.py collectstatic --noinput --settings=learning_platform.settings && python manage.py migrate --settings=learning_platform.settings && python manage.py runserver 0.0.0.0:$PORT --settings=learning_platform.settings" 