[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "nodejs_18"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt",
  "npm install",
  "cd learningplatform_nowy\\ 2/frontend && npm install"
]

[phases.build]
cmds = [
  "cd learningplatform_nowy\\ 2/frontend && npm run build"
]

[start]
cmd = "concurrently \"python manage.py migrate --settings=learning_platform.settings && python manage.py runserver 0.0.0.0:8000 --settings=learning_platform.settings\" \"cd learningplatform_nowy\\ 2/frontend && npm start\"" 