[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && cd learningplatform_nowy2/backend && gunicorn learning_platform.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "django-backend"
sourceDir = "learningplatform_nowy2/backend" 